### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by DedicatedDev** [Lossless-Cash/lossless-v3#104]
if you have to add 1000+ user to your white list, contract will success?
and then it is set value every time for whitelist. 

Mapping has default value when it is initialized. 
so there is no need to set manual false value at all. 

There are more clean data structure in openzeppelin. 

Best.

**Comment by DomantasP** [comment]
Providing large lists in one transaction will always have this gas cap issue. We can easily avoid this issue by whitelisting addresses in batches. Also, we don't think there will be more than a few whitelisted addresses to begin with.

About the default value setting. That's one of the issues the auditors noticed and recommended we do set the default values manually to improve the code consistency.
